language: java
sudo: required
jdk:
  - oraclejdk8
services:
  - docker
before_install:
  - docker pull jboss/wildfly
  - docker build -t brunopacheco1/ceps .
script: 
  - mvn clean package
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push brunopacheco1/ceps;
    fi