language: java
sudo: required
jdk:
  - oraclejdk8
services:
  - docker
before_install:
  - docker pull jboss/wildfly
script: 
  - mvn clean package
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t "$DOCKER_USERNAME/ceps" .;
    else
    docker build -t "$DOCKER_USERNAME/ceps:$TRAVIS_BRANCH" .;
    fi
after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker push "$DOCKER_USERNAME/ceps:latest";
    else
    docker push "$DOCKER_USERNAME/ceps:$TRAVIS_BRANCH";
    fi