language: java
sudo: required
jdk:
  - oraclejdk8
services:
  - docker
before_install:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker pull jboss/wildfly
script: 
  - mvn clean package
  - docker build -t brunopacheco1/ceps .
after_success:
  - docker push brunopacheco1/ceps:latest